#!/usr/bin/env Rscript
# sync-palette.R — propagate the canonical palette (palette.yml) into the four
# house-style files, each of which carries a `>>> kinan palette … <<< kinan palette`
# marked block. The teal lives in four languages (LaTeX \definecolor, CSS custom
# properties, SCSS $vars, R strings) so it can't literally be one file; this makes
# palette.yml the single source and regenerates the four blocks from it. Derived
# values (rgb channels, the rgba string, the flattened light-teal for gt) are
# computed here, not stored. Run after editing palette.yml.

base <- "/Users/kinelhu/.dotfiles/pandoc"
pal  <- yaml::read_yaml(file.path(base, "themes/kinan/palette.yml"))

hex <- toupper(pal$accent); ink <- toupper(pal$ink); sec <- toupper(pal$secondary)
rgb <- as.integer(grDevices::col2rgb(hex))                 # e.g. 39 169 188
rgb_csv  <- paste(rgb, collapse = ", ")
a        <- pal$accent_light_alpha
rgba_str <- sprintf("rgba(%s, %s)", rgb_csv, format(a))    # rgba(39, 169, 188, 0.08)
flat     <- round(255 * (1 - a) + rgb * a)                 # accent flattened on white
flat_hex <- sprintf("#%02X%02X%02X", flat[1], flat[2], flat[3])
pct      <- round(a * 100)                                 # LaTeX AccentPrimary!8!white

replace_block <- function(path, begin, end, block) {
  L <- readLines(path)
  b <- grep(begin, L, fixed = TRUE); e <- grep(end, L, fixed = TRUE)
  if (length(b) != 1 || length(e) != 1 || e < b)
    stop(sprintf("marker mismatch in %s (begin=%d end=%d)", path, length(b), length(e)))
  writeLines(c(if (b > 1) L[1:(b - 1)], block, if (e < length(L)) L[(e + 1):length(L)]), path)
}

replace_block(file.path(base, "templates/house-style.tex"),
  "% >>> kinan palette", "% <<< kinan palette",
  c("% >>> kinan palette — generated by themes/kinan/sync-palette.R; edit palette.yml, not here",
    sprintf("\\definecolor{AccentPrimary}{HTML}{%s}", sub("#", "", hex)),
    sprintf("\\definecolor{TextPrimary}{HTML}{%s}",   sub("#", "", ink)),
    sprintf("\\definecolor{TextSecondary}{HTML}{%s}", sub("#", "", sec)),
    sprintf("\\colorlet{AccentLight}{AccentPrimary!%d!white}", pct),
    "% <<< kinan palette"))

replace_block(file.path(base, "themes/kinan/kinan-report.scss"),
  "// >>> kinan palette", "// <<< kinan palette",
  c("// >>> kinan palette — generated by sync-palette.R; edit palette.yml, not here",
    sprintf("$accent-primary: %s !default;", hex),
    sprintf("$text-primary:   %s !default;", ink),
    sprintf("$text-secondary: %s !default;", sec),
    sprintf("$accent-light:   %s !default;", rgba_str),
    "// <<< kinan palette"))

replace_block(file.path(base, "themes/kinan/kinan-report.css"),
  "/* >>> kinan palette", "/* <<< kinan palette",
  c("/* >>> kinan palette — generated by sync-palette.R; edit palette.yml, not here */",
    ":root {",
    sprintf("  --accent: %s;", hex),
    sprintf("  --accent-rgb: %s;", rgb_csv),
    sprintf("  --ink: %s;", ink),
    sprintf("  --secondary: %s;", sec),
    "}",
    "/* <<< kinan palette */"))

replace_block(file.path(base, "themes/kinan/gt-house.R"),
  "# >>> kinan palette", "# <<< kinan palette",
  c("# >>> kinan palette — generated by sync-palette.R; edit palette.yml, not here",
    sprintf('kin_accent       <- "%s"', hex),
    sprintf('kin_accent_light <- "%s"   # accent at %d%% flattened on white (gt can\'t do the CSS rgba over white)', flat_hex, pct),
    sprintf('kin_ink          <- "%s"', ink),
    "# <<< kinan palette"))

message(sprintf("palette synced: accent=%s ink=%s secondary=%s | rgb=(%s) light=%s (a=%.2f)",
                hex, ink, sec, rgb_csv, flat_hex, a))
